#!/bin/bash

#  to be placed in $HOME/.customize_environment

apt update -y
apt upgrade -y

wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
yes 1 | apt install ./chrome-remote-desktop_current_amd64.deb
rm -rf ./chrome-remote-desktop_current_amd64.deb
sudo DEBIAN_FRONTEND=noninteractive \
    apt install --assume-yes xfce4 desktop-base dbus-x11 xscreensaver
bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
systemctl disable lightdm.service

apt install firefox-esr
